import { SecondBrainDocument, SecondBrainNote, SecondBrainNotebook } from "../types";

export const INITIAL_NOTEBOOKS: SecondBrainNotebook[] = [
  {
    id: "nb_master",
    name: "Master Knowledge Vault",
    description: "National repository of verified Lebanese AI regulations, diaspora syndicates, and technical specs.",
    iconName: "Brain",
    colorTheme: "emerald",
    createdAt: "2026-08-15T10:00:00Z"
  },
  {
    id: "nb_legal",
    name: "Offshore Lex & Law 126/2019",
    description: "Statutory frameworks, 0% corporate tax safe harbor, and BDL clearing rails.",
    iconName: "Scale",
    colorTheme: "amber",
    createdAt: "2026-08-18T14:30:00Z"
  },
  {
    id: "nb_venture",
    name: "Diaspora Venture Syndicates & Pitch",
    description: "Deal memos, Silicon Valley & Paris diaspora bridge pipelines, and term sheets.",
    iconName: "TrendingUp",
    colorTheme: "blue",
    createdAt: "2026-08-20T09:15:00Z"
  },
  {
    id: "nb_compute",
    name: "HPC, GPU Clusters & Models",
    description: "AUB compute grants, distributed inference nodes, and Arabic LLM quantization.",
    iconName: "Cpu",
    colorTheme: "purple",
    createdAt: "2026-08-22T11:00:00Z"
  }
];

export const INITIAL_DOCUMENTS: SecondBrainDocument[] = [
  {
    id: "doc_law126",
    title: "Lebanese Law 126/2019: Offshore Companies, Digital Board Resolutions & 0% Corporate Tax",
    category: "Legal & Regulatory",
    notebookId: "nb_legal",
    sourceType: "whitepaper",
    authorOrSource: "Lebanese Bar Association & Alkharizmi Legal Guild",
    dateAdded: "2026-08-25T08:00:00Z",
    wordCount: 1420,
    tags: ["Law 126/2019", "Offshore S.A.L.", "Tax Exemption", "Corporate Governance"],
    isPinned: true,
    summary: "Complete legal analysis of Law 126/2019 modernizing the Lebanese Code of Commerce, granting 0% corporate income tax for offshore software development and allowing fully remote digital governance.",
    content: `# Lebanese Law No. 126/2019 & Offshore S.A.L. Statutory Framework

## 1. Statutory Foundations
Law No. 126 enacted on March 29, 2019 represents the most comprehensive reform of the Lebanese Code of Commerce (Legislative Decree No. 304/1942) in over seven decades. For technology founders and software studios, this statute works in tandem with Legislative Decree No. 46/1983 and Law 85/2018 governing Offshore Companies (S.A.L. Offshore).

## 2. 0% Corporate Income Tax Regime
- **Export Exemption:** Under Article 1 of Decree 46/1983 as amended, offshore companies operating in Lebanon whose software, algorithms, or digital consulting services are exported abroad are subject to a **flat annual lump-sum tax of 1,000,000 LBP** (~$11 USD).
- **Corporate Profit Tax:** 0% on exported software revenues, software licenses, SaaS subscriptions, and remote engineering contracts.
- **Dividend Distribution:** Dividends paid to non-resident or resident shareholders are exempt from the standard 10% dividend withholding tax when derived from offshore operations.
- **Foreign Ownership:** 100% foreign equity ownership is authorized without any requirement for local Lebanese majority shareholders.

## 3. Digital Board Meetings & Modern Governance
- **Remote Resolutions:** Law 126/2019 permits Board of Directors meetings and General Assemblies to convene via secure videoconferencing and digital quorum.
- **Electronic Signatures:** Ratified board minutes, convertible note issuance, and equity transfers can be authenticated through digital signatures recognized by Lebanese courts.
- **Sole Proprietor / Single Shareholder:** Law 126 introduced the Simplified S.A.R.L. and single-partner corporate structures for early-stage engineering studios.

## 4. IP Assignment & Algorithm Protection
Intellectual property generated by Lebanese engineering teams remains fully protectable under Law No. 75/1999 (Protection of Literary and Artistic Property). Source code, neural net weights, and proprietary training datasets qualify as copyrighted intellectual creations with automatic international Berne Convention reciprocity.`
  },
  {
    id: "doc_diaspora_playbook",
    title: "Diaspora Venture Syndicate Playbook 2026: Paris & Silicon Valley Bridge Architecture",
    category: "Diaspora Capital",
    notebookId: "nb_venture",
    sourceType: "pdf",
    authorOrSource: "NCEI Lebanon & Cedar Syndicate Fund",
    dateAdded: "2026-08-28T12:00:00Z",
    wordCount: 1680,
    tags: ["Diaspora VC", "LebNet", "LIFE London", "SAFE Notes", "Dual-Entity"],
    isPinned: true,
    summary: "Actionable playbook for structuring cross-border venture financing between Lebanese engineering hubs and North American/European diaspora venture networks.",
    content: `# Diaspora Venture Syndicate Playbook 2026: The Transnational DeepTech Bridge

## Executive Thesis
The Lebanese DeepTech ecosystem operates on a high-velocity capital arbitrage model. While senior machine learning talent in San Francisco or London costs $280k–$420k annually, equivalent Ph.D. and senior engineering talent from the American University of Beirut (AUB) or Lebanese American University (LAU) commands $45k–$75k in Fresh USD, delivering a 4.5x runway multiple.

## Syndicate Architecture: The Delaware Flip vs. Dual-Entity Model
Institutional diaspora syndicates (including LebNet Angels, LIFE London Tech Chapter, and Cedar Angels San Francisco) utilize two primary financing rails:

1. **The Dual-Entity Structure (Recommended for Seed/Series A):**
   - **HoldCo:** Delaware C-Corp or French SAS holding all intellectual property, equity options, and enterprise customer agreements.
   - **OpCo:** Lebanese Offshore S.A.L. operating the engineering studio, R&D labs, and payroll in Beirut under a Cost-Plus Transfer Pricing agreement.
   - **Tax Benefit:** HoldCo retains international investor protections while OpCo enjoys 0% local corporate tax and minimal operating overhead.

2. **Standardized Diaspora SAFE Side Letters:**
   - Pre-money valuation caps between $3.5M and $8.0M for Lebanese pre-seed AI startups.
   - MFN (Most Favored Nation) clauses and pro-rata rights for syndicate leads exceeding $100k commitments.
   - Warrant coverage linked to milestone releases: LLM fine-tuning validation, pilot customer deployments in the GCC/Europe.

## Capital Ingestion & Wire Clearance
- Investors remit funds via SWIFT directly into Fresh USD correspondent accounts (Citibank New York / Banque Libano-Française or Bank Audi Beirut).
- Treasury diversification protocols mandate keeping 70% of reserves in offshore treasury bills or multi-currency digital liquidity (USDT/USDC).`
  },
  {
    id: "doc_bdl165",
    title: "BDL Circular 165 & Fresh USD Payment Rails for Lebanese AI Studios",
    category: "Legal & Regulatory",
    notebookId: "nb_legal",
    sourceType: "text",
    authorOrSource: "Banque du Liban & FinTech Working Group",
    dateAdded: "2026-08-30T15:45:00Z",
    wordCount: 1150,
    tags: ["BDL 165", "Fresh USD", "Payment Gateways", "FinTech Clearing"],
    isPinned: false,
    summary: "Technical guide on utilizing BDL Circular 165 for intra-Lebanese fresh electronic settlements and international merchant payouts for SaaS products.",
    content: `# BDL Circular No. 165 & Lebanese FinTech Clearing Infrastructure

## What Circular 165 Solved
Issued by Banque du Liban, Basic Circular No. 165 established a segregated electronic clearing house specifically for "Fresh Funds" (real, unencumbered foreign currencies received after October 2019).

### Core Operational Mechanisms:
1. **Intra-Bank Fresh Electronic Clearing:** Lebanese companies can clear checks and electronic bank transfers in Fresh USD within 24–48 hours across different local commercial banks without incurring prohibitive cash withdrawal fees.
2. **Merchant POS & Payment Links:** Integration with payment providers (Areeba, NetCommerce, Whish Money) enables Lebanese SaaS apps to charge domestic and international credit cards directly into segregated Fresh USD corporate accounts.
3. **Cross-Border Remittances:** Automated routing for export invoicing directly satisfies Central Bank anti-money laundering (AML) Law 44/2015 while guaranteeing 100% repatriation freedom.`
  },
  {
    id: "doc_gpu_cluster",
    title: "AUB & BDD High-Performance GPU Infrastructure Allocation Framework",
    category: "Research & HPC",
    notebookId: "nb_compute",
    sourceType: "whitepaper",
    authorOrSource: "AUB Dept of Electrical & Computer Engineering & BDD",
    dateAdded: "2026-09-02T10:20:00Z",
    wordCount: 1890,
    tags: ["GPU Clusters", "NVIDIA H100", "AUB Research", "LLM Fine-Tuning", "vLLM"],
    isPinned: false,
    summary: "Cluster specifications, compute grant quotas, and model quantization protocols for Lebanese machine learning startups utilizing regional computing nodes.",
    content: `# Sovereign GPU Compute Allocation & Optimization Framework

## 1. Regional Compute Grid Specifications
The academic-private consortium established between AUB, BDD, and diaspora cloud providers maintains a dedicated distributed node pool:
- **Primary Node Cluster:** 32x NVIDIA H100 SXM5 (80GB VRAM each) and 64x NVIDIA A100 (40GB) interconnected with 400Gbps InfiniBand.
- **Secondary Edge Fleet:** 128x RTX 4090 nodes located at Beirut Digital District for cost-effective inference and testing.

## 2. Ingestion & Compute Grant Program
- Early-stage AI startups registered in the 961AI directory can apply for up to **$25,000 in subsidized compute credits**.
- Criteria: Must feature a minimum 50% Lebanese engineering team and commit open weights or published benchmarks to the sovereign repository.

## 3. Recommended Optimization Stacks for Low-Bandwidth Infrastructure
Due to variable Lebanese terrestrial fiber conditions, engineering teams are required to employ high-efficiency deployment pipelines:
- **Inference Server:** vLLM with PagedAttention or TensorRT-LLM.
- **Quantization:** AWQ 4-bit and FP8 quantization for 70B parameter models, cutting memory footprints by 65% with zero loss in Arabic dialect benchmark accuracy.
- **Speculative Decoding:** Paired small draft models (e.g. Qwen2.5-Coder-1.5B) accelerating larger base models by 2.2x.`
  },
  {
    id: "doc_pitch_checklist",
    title: "961AI Sovereign Technical Diligence & Safe Harbor IP Safeguards",
    category: "Pitch Deck & Financials",
    notebookId: "nb_venture",
    sourceType: "markdown",
    authorOrSource: "961AI Technical Review Committee",
    dateAdded: "2026-09-04T16:00:00Z",
    wordCount: 1340,
    tags: ["Due Diligence", "IP Safeguards", "Pitch Deck", "Code Quality", "Security"],
    isPinned: false,
    summary: "Comprehensive diligence checklist used by diaspora VCs to evaluate Lebanese software architectures, data isolation, and licensing models.",
    content: `# Technical Due Diligence & Sovereign IP Safeguards

## Pillar 1: Code Ownership & Contributor Agreements
- Every software engineer, contractor, or intern based in Lebanon must sign a comprehensive Proprietary Information and Inventions Agreement (PIIA).
- Formal reference to Lebanese Copyright Law 75/1999 Article 12, explicitly transferring moral and economic exploitation rights to the corporate entity.

## Pillar 2: Data Pipeline & Model Lineage
- Clear documentation of training corpora: Ensure no copyrighted Arabic literature or unlicensed scrapings contaminate model fine-tuning checkpoints.
- Use of synthetic data pipelines generated through commercial enterprise licenses.

## Pillar 3: Wartime & Redundancy Resilience
- Multi-cloud architecture: Automated failover across European regions (Frankfurt, Paris) and local offline-capable edge caches in Beirut.
- Local power and internet continuity: Minimum tier-3 backup power (solar + UPS) at development facilities, backed by Starlink satellite connectivity where permitted.`
  }
];

export const INITIAL_NOTES: SecondBrainNote[] = [
  {
    id: "note_1",
    title: "Key Takeaways: Setting Up Our Offshore S.A.L. in Beirut",
    notebookId: "nb_legal",
    content: `## Action Plan for Law 126/2019 Incorporation
1. File articles of association with the Beirut Commercial Registry (Sijil Tijari).
2. Deposit minimum capital of 30,000,000 LBP in an escrow bank account.
3. Appoint a licensed Lebanese Bar Association attorney on statutory retainer.
4. Execute digital board minutes approving initial SAFE note issuances for diaspora angels.
*Citation:* See Law 126/2019 reference doc for exact tax schedule details.`,
    updatedAt: "2026-09-05T14:10:00Z",
    tags: ["Action Plan", "Legal", "Setup"],
    linkedDocIds: ["doc_law126", "doc_bdl165"],
    isPinned: true
  },
  {
    id: "note_2",
    title: "Cedar Syndicate Pitch Notes: Paris & SF Feedback",
    notebookId: "nb_venture",
    content: `## Investor Feedback Summary
- Paris angels loved the 4.5x talent cost efficiency in Beirut.
- Requested explicit clarification on BDL Circular 165 for international SaaS receivables.
- Action item: Draft dual-entity structure (Delaware HoldCo + Beirut Offshore S.A.L. OpCo).
- Next meeting scheduled with LebNet DeepTech lead next Tuesday.`,
    updatedAt: "2026-09-06T09:30:00Z",
    tags: ["Pitch Notes", "Fundraising", "Feedback"],
    linkedDocIds: ["doc_diaspora_playbook", "doc_pitch_checklist"],
    isPinned: false
  },
  {
    id: "note_3",
    title: "AUB H100 Cluster Application Checklist",
    notebookId: "nb_compute",
    content: `## Compute Grant Application
- Required benchmark: 4-bit quantized Arabic dialect extraction model.
- Estimated GPU hours: 120 hours on 8x H100 SXM5 cluster.
- Submit benchmark paper to AUB ECE department for grant credit approval.`,
    updatedAt: "2026-09-07T11:20:00Z",
    tags: ["Compute", "AUB", "GPU"],
    linkedDocIds: ["doc_gpu_cluster"],
    isPinned: false
  }
];
